### PR TITLE
If request is cancelled or returns 0 fire callback

### PR DESCRIPTION
**Pull request by sidonaldson**
I added this code in so that if readystate === 4 and status === 0 if fires the callback.
This enables it to work offline and in kiosk mode.

What do you think?

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
so this will hick in if the browser is offline and is able to retrieve it from cache?

**Comment by sidonaldson** [comment]
I noticed there was an issue raised where the user wanted this to work locally and not via a webserver - that's what I meant by offline. Sorry my bad on that one.
If you open chrome with the flag --allow-file-access-from-files all ajax calls work elsewhere such as angularjs but the callback doesn't fire in this case and that's because the status returns 0. I believe that only exists if the user cancels the request or navigates away from the page before it completes.
If you make this amend your code works perfectly in a local environment!

**Comment by calvinmetcalf** [comment]
why don't you just do `request.status < 400`

**Comment by sidonaldson** [comment]
even better! :)

**Comment by calvinmetcalf** [comment]
so a invalid cross origin request also has a response of 0 so I'm going to change it so you have to explicitly say if your doing it locally.

**Pull request merged**
