### PR TITLE
Add callback to dataLoadComplete

### PR DESCRIPTION
**Pull request by sidonaldson**
Use case:

new L.GeoJSON.AJAX(url, {
    onComplete: function(layers){
         //fade in
    }
}).addTo(map);

What do you think? Is there a way to attach a listener using .on()?

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
my idea was that a person could listen for the event if they wanted to do that, i.e. a person can go `myLayer.on('dataLoadComplete',function(){})`

**Comment by calvinmetcalf** [comment]
after #17 it'll be `myLayer.on('data:loaded',function(){})` to make it work better with leaflet spinner, which I had though tI had already done

**Comment by calvinmetcalf** [comment]
so yes to do what you asked

``` javascript
new L.GeoJSON.AJAX(url, {
onComplete: function(layers){
//fade in
}
}).addTo(map);
```

fist off you'd either want to put the whole thing in parentheses or use the factory version because what you have won't don what you think it will, so either

``` javascript
new (L.GeoJSON.AJAX(url, {
onComplete: function(layers){
//fade in
}
})).addTo(map);
```

or

``` javascript
L.geoJson.ajax(url, {
onComplete: function(layers){
//fade in
}
}).addTo(map);
```

I prefer the latter version but it's a matter of taste, now to get it to do something when it is done loading, like say wait until it's done loading everything before adding it, as currently it will download the data when it's created and add it to its layers when they download, but if you add it to the map before it's done downloading an empty layer is added that will be filled whenever things get downloaded, i.e.

``` javascript
var layer = L.geoJson.ajax([url1,url2]);//downloading starts, 'data:loading' fired
layer.addTo(map);//empty geojson added to map
//url1 downloads 'data:progress' fired, contents of url1 added to map
//url2 downloads 'data:progress' fired, contents of url2 added to map 'data:loaded' fired
```

if you wanted url1 and url2 to be added to the map together

``` javascript
var layer = L.geoJson.ajax([url1,url2]);
layer.on('data:loaded',function(){
    layer.addTo(map);
});
```

**Comment by sidonaldson** [comment]
Cheers for clearing this up Calvin.

I had spotted your custom events in the code but couldn't get the to work so incorrectly assumed they were not public - what actually was wrong was that I was adding the layer to the map immediately and then attaching the event.
So, like your example above, load the content first and then attach it on 'load'!
It's best practice with LeafletJS to add the layer after populating it so I'm annoyed I missed it.
One last thing - you might want to stick your detailed explanation in the docs in case someone else needs it :)

**Comment by calvinmetcalf** [comment]
so previously the following would not work,

``` javascript
var layer = L.geoJson.ajax(url).addTo(map);
layer.on('blah',function(){});
```

but that WILL work now as there is an async wait there. 

I did update the README a couple days ago if you still think it's unclear feel free to send a pull request :smile:

**Comment by sidonaldson** [comment]
Ah good job!

**Pull request closed without merging**
